services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=DEV
      - DATABASE_URL=postgres://postgres:password@db:5432/hono
      - PORT=8000
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - db
      - cache
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hono
    ports:
      - "5432:5432"

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
