# fly.toml app configuration file generated for hono-open-api-starter on 2025-06-21T03:01:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hono-open-api-starter'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = "production"
  PORT = "8000"
  HOST = "0.0.0.0"